
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })
import "bulma/css/bulma.css"
import StoreProvider from './StoreProvider'
import Navbar from './components/Navbar'
import NextTopLoader from 'nextjs-toploader'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Navbar />
          <NextTopLoader />
          {children}
       </StoreProvider>
      
      </body>
    </html>
  )
}
